### ISSUE TITLE
Can't download carlate.exe

### ISSUE THREAD

**Issue by turrnut** [ademyrodev/carlate#8]
![image](https://user-images.githubusercontent.com/104261407/204932617-cb402385-0b87-49db-9fde-202c7c078eb3.png)

**Comment by turrnut** [comment]
help Help **HELP**

**Comment by ademyrodev** [comment]
oh sorry

**Comment by ademyrodev** [comment]
I might be a bit late, but here's what you can do:
Try running ``git clone https://github.com/ademyrodev/carlate.git`` on your terminal
carlate.exe should be show up automatically.

Now, there's an issue with ``carlate.exe``: it is outdated.
To update it, run ``gcc -o carlate main.c chunk.c compiler.c debug.c error.c memory.c object.c scan.c table.c value.c vm.c utils/dstring.c``. (You can just copy the command)

Keep in mind that ``carlate`` is built under an Unix system, so it might not work 100% correctly on windows.

Now, to execute your code, run:

CMD:
```cmd
> .\carlate.exe filename.crlt
```

Powershell:
```powershell
> ./carlate filename.crlt
```

**Comment by ademyrodev** [comment]
If any of the commands don't work, you should install ``git`` and/or ``gcc``.
Send another comment if you encountered any other issue.

**Comment by turrnut** [comment]
Thanks, its working now
